# Generated by Django 5.2.15 on 2026-07-30 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, help_text='Custom name provided during upload', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='database/')),
                ('source_filename', models.CharField(max_length=255)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='database_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='Labour_master_Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_ID', models.IntegerField(db_index=True)),
                ('Category', models.CharField(blank=True, max_length=255, null=True)),
                ('Sub_Category', models.CharField(blank=True, max_length=255, null=True)),
                ('Class', models.CharField(blank=True, max_length=255, null=True)),
                ('Size', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Unit', models.CharField(blank=True, max_length=100, null=True)),
                ('Capacity', models.CharField(blank=True, max_length=255, null=True)),
                ('Attribute', models.TextField(blank=True, null=True)),
                ('Labour_Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Base_Rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Size_Factor', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('Labour_Rate_Per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Testing_Labour_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Scaffolding_Labour_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Consumables_Labour_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Painting_Labour_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Labour_Buffer_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Total_Labour_per_Unit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Total_Labour_per_unit_with_labour_Multipler', models.DecimalField(blank=True, db_column='Total_Labour_per_unit_with_labour_Multipler', decimal_places=2, max_digits=18, null=True)),
                ('database_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_master_output_rows', to='database_manager.databaseversion')),
            ],
            options={
                'db_table': 'Labour_master_Output',
            },
        ),
        migrations.CreateModel(
            name='Rate_Master_Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rate_ID', models.IntegerField(blank=True, db_index=True, null=True)),
                ('Product_ID', models.IntegerField(db_index=True)),
                ('Category', models.CharField(blank=True, max_length=255, null=True)),
                ('Sub_Category', models.CharField(blank=True, max_length=255, null=True)),
                ('Class', models.CharField(blank=True, max_length=255, null=True)),
                ('Size', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Unit', models.CharField(blank=True, max_length=100, null=True)),
                ('Capacity', models.CharField(blank=True, max_length=255, null=True)),
                ('Attribute', models.TextField(blank=True, null=True)),
                ('Make', models.CharField(blank=True, max_length=255, null=True)),
                ('Vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('Base_Purchase_Rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Last_Updated', models.DateTimeField(blank=True, null=True)),
                ('Discount', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('Net_Material_Rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Procurement_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Commercial_Material_Base', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Accessories_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Handling_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Wastage_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Sub_Total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Profit_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Final_Material_Amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Margin_pct_on_Selling', models.DecimalField(blank=True, db_column='Margin_pct_on_Selling', decimal_places=8, max_digits=18, null=True)),
                ('database_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_master_output_rows', to='database_manager.databaseversion')),
            ],
            options={
                'db_table': 'Rate_Master_Output',
            },
        ),
        migrations.AddConstraint(
            model_name='databaseversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='uniq_active_database_version'),
        ),
        migrations.AddIndex(
            model_name='labour_master_output',
            index=models.Index(fields=['database_version', 'Product_ID'], name='Labour_mast_databas_bd08c1_idx'),
        ),
        migrations.AddConstraint(
            model_name='labour_master_output',
            constraint=models.UniqueConstraint(fields=('database_version', 'Product_ID'), name='uniq_labour_product_per_version'),
        ),
        migrations.AddIndex(
            model_name='rate_master_output',
            index=models.Index(fields=['database_version', 'Product_ID'], name='Rate_Master_databas_d3c64a_idx'),
        ),
        migrations.AddIndex(
            model_name='rate_master_output',
            index=models.Index(fields=['database_version', 'Rate_ID'], name='Rate_Master_databas_f1dbb5_idx'),
        ),
        migrations.AddIndex(
            model_name='rate_master_output',
            index=models.Index(fields=['database_version', 'Category', 'Sub_Category'], name='Rate_Master_databas_d7b127_idx'),
        ),
    ]
