# Generated by Django 5.2.15 on 2026-06-23 15:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(db_index=True, max_length=255)),
                ('product_code', models.CharField(db_index=True, max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Product aliases',
            },
        ),
        migrations.CreateModel(
            name='ProductEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(db_index=True, max_length=100)),
                ('embedding_vector', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StateControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=150, unique=True)),
                ('labour_multiplier', models.DecimalField(decimal_places=4, default=1, max_digits=8)),
                ('transportation_multiplier', models.DecimalField(decimal_places=4, default=1, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('source_filename', models.CharField(max_length=255)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='database_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='LabourMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour_code', models.CharField(db_index=True, max_length=100)),
                ('labour_name', models.CharField(max_length=255)),
                ('labour_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('database_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_rates', to='database_manager.databaseversion')),
            ],
        ),
        migrations.CreateModel(
            name='TORAccessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tor_code', models.CharField(db_index=True, max_length=100)),
                ('accessory_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('database_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tor_accessories', to='database_manager.databaseversion')),
            ],
        ),
        migrations.CreateModel(
            name='TORLabour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tor_code', models.CharField(db_index=True, max_length=100)),
                ('labour_code', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('database_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tor_labour', to='database_manager.databaseversion')),
            ],
        ),
        migrations.CreateModel(
            name='TORMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tor_code', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('database_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tor_main', to='database_manager.databaseversion')),
            ],
        ),
        migrations.CreateModel(
            name='RateMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField()),
                ('make', models.CharField(blank=True, max_length=150)),
                ('vendor', models.CharField(blank=True, max_length=150)),
                ('purchase_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=150)),
                ('subcategory', models.CharField(blank=True, max_length=150)),
                ('remarks', models.TextField(blank=True)),
                ('database_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='database_manager.databaseversion')),
            ],
            options={
                'indexes': [models.Index(fields=['database_version', 'product_code'], name='database_ma_databas_43c9b2_idx')],
            },
        ),
    ]
