# Generated by Django 5.2.15 on 2026-07-10 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(blank=True, help_text='Custom name provided during upload', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=False)),
                ('file', models.FileField(blank=True, null=True, upload_to='database/')),
                ('source_filename', models.CharField(max_length=255)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='database_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='Labour_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tech_Key', models.CharField(db_index=True, max_length=255)),
                ('Size', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Labour_Type', models.CharField(blank=True, max_length=255, null=True)),
                ('Base_Rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Size_Factor', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('Labour_Rate_Per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Testing_Labour_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Scaffolding_Labour_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Consumables_Labour_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Painting_Labour_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Labour_Buffer_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Total_Labour_per_Unit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Labour_Multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('Total_Labour_per_unit_with_labour_Multipler', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('database_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_master_rows', to='database_manager.databaseversion')),
            ],
            options={
                'db_table': 'Labour_Master',
            },
        ),
        migrations.CreateModel(
            name='Labour_Structure_Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=255, null=True)),
                ('Sub_Category', models.CharField(blank=True, max_length=255, null=True)),
                ('Size', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Unit', models.CharField(blank=True, max_length=100, null=True)),
                ('Tech_Key', models.CharField(blank=True, max_length=255, null=True)),
                ('database_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_structure_rows', to='database_manager.databaseversion')),
            ],
            options={
                'db_table': 'Labour_Structure_Source',
            },
        ),
        migrations.CreateModel(
            name='Rate_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=255, null=True)),
                ('Sub_Category', models.CharField(blank=True, max_length=255, null=True)),
                ('Class', models.CharField(blank=True, max_length=255, null=True)),
                ('Size', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Make', models.CharField(blank=True, max_length=255, null=True)),
                ('Capacity', models.CharField(blank=True, max_length=255, null=True)),
                ('Unit', models.CharField(blank=True, max_length=100, null=True)),
                ('Attribute', models.TextField(blank=True, null=True)),
                ('Supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('Base_Purchase_Rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Discount_Percent', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('Net_Material_Rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Tech_Key', models.CharField(db_index=True, max_length=255)),
                ('Last_Updated', models.DateTimeField(blank=True, null=True)),
                ('Procurement_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Commercial_Material_Base', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Accessories_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Handling_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Wastage_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Subtotal_Before_Profit', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Profit_Value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Final_Expenditure', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Final_Amount_Excl_GST', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Margin_Percent_On_Selling', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('database_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_master_rows', to='database_manager.databaseversion')),
            ],
            options={
                'db_table': 'Rate_Master',
            },
        ),
        migrations.CreateModel(
            name='State_Control_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('State', models.CharField(max_length=255)),
                ('Labour_Multiplier', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('database_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_control_rows', to='database_manager.databaseversion')),
            ],
            options={
                'db_table': 'State_Control_List',
            },
        ),
        migrations.CreateModel(
            name='TOR_Accessories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=255, null=True)),
                ('Sub_Category', models.CharField(blank=True, max_length=255, null=True)),
                ('Min_Size', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Max_Size', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('Accessories_Percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('database_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tor_accessories_rows', to='database_manager.databaseversion')),
            ],
            options={
                'db_table': 'TOR_Accessories',
            },
        ),
        migrations.CreateModel(
            name='TOR_Labour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Testing_Percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('Scaffolding_Percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('Consumables_Percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('Painting_Rate', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('Labour_Buffer_Percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('database_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tor_labour_rows', to='database_manager.databaseversion')),
            ],
            options={
                'db_table': 'TOR_Labour',
            },
        ),
        migrations.CreateModel(
            name='TOR_Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(blank=True, max_length=255, null=True)),
                ('Handling_Percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('Wastage_Percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('Profit_Percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('Procurement_Percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('Risk_Buffer_Percent', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('Project_State', models.CharField(blank=True, max_length=255, null=True)),
                ('database_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tor_main_rows', to='database_manager.databaseversion')),
            ],
            options={
                'db_table': 'TOR_Main',
            },
        ),
        migrations.AddConstraint(
            model_name='databaseversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='uniq_active_database_version'),
        ),
        migrations.AddIndex(
            model_name='rate_master',
            index=models.Index(fields=['database_version', 'Tech_Key'], name='Rate_Master_databas_50980e_idx'),
        ),
        migrations.AddConstraint(
            model_name='state_control_list',
            constraint=models.UniqueConstraint(fields=('database_version', 'State'), name='uniq_state_control_per_version'),
        ),
    ]
