# Generated by Django 5.2.15 on 2026-06-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labourmaster',
            name='spec_json',
            field=models.JSONField(blank=True, default=dict, help_text='All raw Excel columns stored as key-value pairs.'),
        ),
        migrations.AddField(
            model_name='ratemaster',
            name='spec_json',
            field=models.JSONField(blank=True, default=dict, help_text='All raw Excel columns stored as key-value pairs.'),
        ),
        migrations.AddField(
            model_name='toraccessories',
            name='spec_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='torlabour',
            name='spec_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tormain',
            name='spec_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
