# Generated by Django 5.2.15 on 2026-07-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labour_master_output',
            name='Product_ID',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='rate_master_output',
            name='Product_ID',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='rate_master_output',
            name='Rate_ID',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
