# Generated by Django 5.2.15 on 2026-07-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0002_labourmaster_spec_json_ratemaster_spec_json_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseversion',
            name='name',
            field=models.CharField(blank=True, help_text='Custom name provided during upload', max_length=255),
        ),
    ]
