# Generated by Django 5.2.15 on 2026-07-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0003_databaseversion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseversion',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='database/'),
        ),
    ]
