# Generated by Django 5.2.15 on 2026-08-24 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0003_product_helper'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='product_helper',
            new_name='Product_Hel_databas_585d42_idx',
            old_name='Product_Hel_databas_7c1a2b_idx',
        ),
        migrations.RenameIndex(
            model_name='product_helper',
            new_name='Product_Hel_databas_fa5bd2_idx',
            old_name='Product_Hel_databas_9d4e3f_idx',
        ),
    ]
