# Align master tables with workbook PascalCase columns and sheet table names.

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database_manager", "0006_restructure_master_schema"),
    ]

    operations = [
        migrations.RenameField(
            model_name="materialrate",
            old_name="category",
            new_name="Category",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="sub_category",
            new_name="Sub_Category",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="material_class",
            new_name="Class",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="size",
            new_name="Size",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="make",
            new_name="Make",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="capacity",
            new_name="Capacity",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="unit",
            new_name="Unit",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="attribute",
            new_name="Attribute",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="supplier",
            new_name="Supplier",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="base_purchase_rate",
            new_name="Base_Purchase_Rate",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="discount_percent",
            new_name="Discount_Percent",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="net_material_rate",
            new_name="Net_Material_Rate",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="tech_key",
            new_name="Tech_Key",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="last_updated",
            new_name="Last_Updated",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="procurement_value",
            new_name="Procurement_Value",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="commercial_material_base",
            new_name="Commercial_Material_Base",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="accessories_value",
            new_name="Accessories_Value",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="handling_value",
            new_name="Handling_Value",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="wastage_value",
            new_name="Wastage_Value",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="subtotal_before_profit",
            new_name="Subtotal_Before_Profit",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="profit_value",
            new_name="Profit_Value",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="final_expenditure",
            new_name="Final_Expenditure",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="final_amount_excl_gst",
            new_name="Final_Amount_Excl_GST",
        ),
        migrations.RenameField(
            model_name="materialrate",
            old_name="margin_percent",
            new_name="Margin_Percent_On_Selling",
        ),
        migrations.RenameModel(
            old_name="MaterialRate",
            new_name="Rate_Master",
        ),
        migrations.AlterModelTable(
            name="rate_master",
            table="Rate_Master",
        ),
        migrations.RenameField(
            model_name="labourmaster",
            old_name="tech_key",
            new_name="Tech_Key",
        ),
        migrations.RenameField(
            model_name="labourmaster",
            old_name="size",
            new_name="Size",
        ),
        migrations.RenameField(
            model_name="labourmaster",
            old_name="labour_type",
            new_name="Labour_Type",
        ),
        migrations.RenameField(
            model_name="labourmaster",
            old_name="base_rate",
            new_name="Base_Rate",
        ),
        migrations.RenameField(
            model_name="labourmaster",
            old_name="size_factor",
            new_name="Size_Factor",
        ),
        migrations.RenameField(
            model_name="labourmaster",
            old_name="labour_rate_per_unit",
            new_name="Labour_Rate_Per_unit",
        ),
        migrations.RenameField(
            model_name="labourmaster",
            old_name="testing_labour_value",
            new_name="Testing_Labour_Value",
        ),
        migrations.RenameField(
            model_name="labourmaster",
            old_name="scaffolding_labour_value",
            new_name="Scaffolding_Labour_Value",
        ),
        migrations.RenameField(
            model_name="labourmaster",
            old_name="consumables_labour_value",
            new_name="Consumables_Labour_Value",
        ),
        migrations.RenameField(
            model_name="labourmaster",
            old_name="painting_labour_value",
            new_name="Painting_Labour_Value",
        ),
        migrations.RenameField(
            model_name="labourmaster",
            old_name="labour_buffer_value",
            new_name="Labour_Buffer_Value",
        ),
        migrations.RenameField(
            model_name="labourmaster",
            old_name="total_labour_per_unit",
            new_name="Total_Labour_per_Unit",
        ),
        migrations.RenameField(
            model_name="labourmaster",
            old_name="labour_multiplier",
            new_name="Labour_Multiplier",
        ),
        migrations.RenameField(
            model_name="labourmaster",
            old_name="total_labour_with_multiplier",
            new_name="Total_Labour_per_unit_with_labour_Multipler",
        ),
        migrations.RenameModel(
            old_name="LabourMaster",
            new_name="Labour_Master",
        ),
        migrations.AlterModelTable(
            name="labour_master",
            table="Labour_Master",
        ),
        migrations.RemoveConstraint(
            model_name="categoryconfig",
            name="uniq_category_config_per_version",
        ),
        migrations.RenameField(
            model_name="categoryconfig",
            old_name="category",
            new_name="Category",
        ),
        migrations.RenameField(
            model_name="categoryconfig",
            old_name="handling_percent",
            new_name="Handling_Percent",
        ),
        migrations.RenameField(
            model_name="categoryconfig",
            old_name="wastage_percent",
            new_name="Wastage_Percent",
        ),
        migrations.RenameField(
            model_name="categoryconfig",
            old_name="profit_percent",
            new_name="Profit_Percent",
        ),
        migrations.RenameField(
            model_name="categoryconfig",
            old_name="procurement_percent",
            new_name="Procurement_Percent",
        ),
        migrations.RenameField(
            model_name="categoryconfig",
            old_name="risk_buffer_percent",
            new_name="Risk_Buffer_Percent",
        ),
        migrations.RenameField(
            model_name="categoryconfig",
            old_name="project_state",
            new_name="Project_State",
        ),
        migrations.RenameModel(
            old_name="CategoryConfig",
            new_name="TOR_Main",
        ),
        migrations.AlterModelTable(
            name="tor_main",
            table="TOR_Main",
        ),
        migrations.RenameField(
            model_name="labourconfig",
            old_name="testing_percent",
            new_name="Testing_Percent",
        ),
        migrations.RenameField(
            model_name="labourconfig",
            old_name="scaffolding_percent",
            new_name="Scaffolding_Percent",
        ),
        migrations.RenameField(
            model_name="labourconfig",
            old_name="consumables_percent",
            new_name="Consumables_Percent",
        ),
        migrations.RenameField(
            model_name="labourconfig",
            old_name="painting_rate",
            new_name="Painting_Rate",
        ),
        migrations.RenameField(
            model_name="labourconfig",
            old_name="labour_buffer_percent",
            new_name="Labour_Buffer_Percent",
        ),
        migrations.RenameModel(
            old_name="LabourConfig",
            new_name="TOR_Labour",
        ),
        migrations.AlterModelTable(
            name="tor_labour",
            table="TOR_Labour",
        ),
        migrations.RenameField(
            model_name="accessoriesrule",
            old_name="category",
            new_name="Category",
        ),
        migrations.RenameField(
            model_name="accessoriesrule",
            old_name="sub_category",
            new_name="Sub_Category",
        ),
        migrations.RenameField(
            model_name="accessoriesrule",
            old_name="min_size",
            new_name="Min_Size",
        ),
        migrations.RenameField(
            model_name="accessoriesrule",
            old_name="max_size",
            new_name="Max_Size",
        ),
        migrations.RenameField(
            model_name="accessoriesrule",
            old_name="accessories_percent",
            new_name="Accessories_Percent",
        ),
        migrations.RenameModel(
            old_name="AccessoriesRule",
            new_name="TOR_Accessories",
        ),
        migrations.AlterModelTable(
            name="tor_accessories",
            table="TOR_Accessories",
        ),
        migrations.RenameField(
            model_name="statemultiplier",
            old_name="state",
            new_name="State",
        ),
        migrations.RenameField(
            model_name="statemultiplier",
            old_name="labour_multiplier",
            new_name="Labour_Multiplier",
        ),
        migrations.RenameModel(
            old_name="StateMultiplier",
            new_name="State_Control_List",
        ),
        migrations.AlterModelTable(
            name="state_control_list",
            table="State_Control_List",
        ),
        migrations.RemoveConstraint(
            model_name="state_control_list",
            name="uniq_state_multiplier_per_version",
        ),
        migrations.AddConstraint(
            model_name="state_control_list",
            constraint=models.UniqueConstraint(
                fields=("database_version", "State"),
                name="uniq_state_control_per_version",
            ),
        ),
        migrations.CreateModel(
            name="Labour_Structure_Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Category",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "Sub_Category",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "Size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "Unit",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "Tech_Key",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "database_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labour_structure_rows",
                        to="database_manager.databaseversion",
                    ),
                ),
            ],
            options={
                "db_table": "Labour_Structure_Source",
            },
        ),
    ]
