# Generated by Django 5.2.15 on 2026-07-10 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_manager', '0008_repair_labour_structure_columns'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='rate_master',
            name='database_ma_databas_faf569_idx',
        ),
        migrations.AlterField(
            model_name='labour_master',
            name='Base_Rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='labour_master',
            name='Consumables_Labour_Value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='labour_master',
            name='Labour_Buffer_Value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='labour_master',
            name='Labour_Multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='labour_master',
            name='Labour_Rate_Per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='labour_master',
            name='Labour_Type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labour_master',
            name='Painting_Labour_Value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='labour_master',
            name='Scaffolding_Labour_Value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='labour_master',
            name='Size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='labour_master',
            name='Size_Factor',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='labour_master',
            name='Tech_Key',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='labour_master',
            name='Testing_Labour_Value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='labour_master',
            name='Total_Labour_per_Unit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='labour_master',
            name='Total_Labour_per_unit_with_labour_Multipler',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='labour_master',
            name='database_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labour_master_rows', to='database_manager.databaseversion'),
        ),
        migrations.AlterField(
            model_name='labour_structure_source',
            name='Category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labour_structure_source',
            name='Sub_Category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labour_structure_source',
            name='Tech_Key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='labour_structure_source',
            name='Unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='Accessories_Value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='Attribute',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='Base_Purchase_Rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='Capacity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='Category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='Class',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='Commercial_Material_Base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='Discount_Percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='Final_Amount_Excl_GST',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='Final_Expenditure',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='Handling_Value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='Make',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='Margin_Percent_On_Selling',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='Net_Material_Rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='Procurement_Value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='Profit_Value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='Size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='Sub_Category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='Subtotal_Before_Profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='Supplier',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='Unit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='Wastage_Value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='rate_master',
            name='database_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_master_rows', to='database_manager.databaseversion'),
        ),
        migrations.AlterField(
            model_name='state_control_list',
            name='Labour_Multiplier',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='state_control_list',
            name='State',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='state_control_list',
            name='database_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_control_rows', to='database_manager.databaseversion'),
        ),
        migrations.AlterField(
            model_name='tor_accessories',
            name='Accessories_Percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tor_accessories',
            name='Category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tor_accessories',
            name='Max_Size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='tor_accessories',
            name='Min_Size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='tor_accessories',
            name='Sub_Category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tor_accessories',
            name='database_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tor_accessories_rows', to='database_manager.databaseversion'),
        ),
        migrations.AlterField(
            model_name='tor_labour',
            name='Consumables_Percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tor_labour',
            name='Labour_Buffer_Percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tor_labour',
            name='Painting_Rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='tor_labour',
            name='Scaffolding_Percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tor_labour',
            name='Testing_Percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tor_labour',
            name='database_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tor_labour_rows', to='database_manager.databaseversion'),
        ),
        migrations.AlterField(
            model_name='tor_main',
            name='Category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tor_main',
            name='Handling_Percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tor_main',
            name='Procurement_Percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tor_main',
            name='Profit_Percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tor_main',
            name='Project_State',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tor_main',
            name='Risk_Buffer_Percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tor_main',
            name='Wastage_Percent',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='tor_main',
            name='database_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tor_main_rows', to='database_manager.databaseversion'),
        ),
        migrations.AddIndex(
            model_name='rate_master',
            index=models.Index(fields=['database_version', 'Tech_Key'], name='Rate_Master_databas_50980e_idx'),
        ),
    ]
