# Generated by Django 5.2.15 on 2026-07-08 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MakeListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(db_index=True, max_length=150)),
                ('category', models.CharField(blank=True, max_length=150)),
                ('boq_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='make_list_entries', to='boq.boqrun')),
            ],
            options={
                'verbose_name_plural': 'Make list entries',
            },
        ),
    ]
