# Generated by Django 5.2.15 on 2026-07-10 18:12

import apps.boq.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boq_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded')], default='UPLOADED', max_length=20)),
                ('uploaded_file', models.FileField(upload_to=apps.boq.models.boq_upload_path)),
                ('make_list_file', models.FileField(blank=True, null=True, upload_to=apps.boq.models.make_list_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boqs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BOQ',
                'verbose_name_plural': 'BOQs',
                'ordering': ['-created_at'],
            },
        ),
    ]
