# Generated by Django 5.2.15 on 2026-07-08 19:01

import apps.boq.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BOQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boq_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('EXPORTED', 'Exported')], default='UPLOADED', max_length=20)),
                ('uploaded_file', models.FileField(upload_to=apps.boq.models.boq_upload_path)),
                ('make_list_file', models.FileField(blank=True, null=True, upload_to=apps.boq.models.make_list_upload_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boqs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BOQ',
                'verbose_name_plural': 'BOQs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BOQRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('original_headers', models.JSONField(blank=True, null=True)),
                ('boq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='boq.boq')),
            ],
            options={
                'ordering': ['boq', '-run_number'],
                'unique_together': {('boq', 'run_number')},
            },
        ),
        migrations.CreateModel(
            name='BOQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('target_excel_row', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('original_data', models.JSONField(blank=True, null=True)),
                ('row_json', models.JSONField(blank=True, null=True)),
                ('ai_extraction', models.JSONField(blank=True, null=True)),
                ('boq_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='boq.boqrun')),
            ],
            options={
                'ordering': ['boq_run', 'row_number'],
            },
        ),
    ]
