# Generated by Django 5.2.15 on 2026-06-23 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqitem',
            name='ai_extraction',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
