# Generated by Django 5.2.15 on 2026-07-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boq", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="boq",
            name="boq_data",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="boq",
            name="make_list_data",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
