# Generated by Django 5.2.15 on 2026-07-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0002_boqitem_ai_extraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqitem',
            name='original_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
