# Generated by Django 5.2.15 on 2026-07-13 15:59

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0002_boq_normalized_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='boq',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('boq_name'), name='boq_unique_name_ci'),
        ),
    ]
