# Generated by Django 5.2.15 on 2026-07-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0003_boq_unique_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='boq',
            name='analysis_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='boq',
            name='status',
            field=models.CharField(choices=[('UPLOADED', 'Uploaded'), ('PROCESSING', 'Processing'), ('PROCESSED', 'Processed'), ('ANALYSIS_FAILED', 'Analysis Failed')], default='UPLOADED', max_length=20),
        ),
    ]
