# Generated by Django 5.2.15 on 2026-07-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0003_boqitem_original_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqrun',
            name='original_headers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
