# Generated by Django 5.2.15 on 2026-07-13 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boq', '0004_analysis_data_and_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='boq',
            name='review_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
