# Generated by Django 5.2.15 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boq", "0007_boq_extracted_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boq",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPLOADED", "Uploaded"),
                    ("PROCESSING", "Processing"),
                    ("EXTRACTED", "Extracted"),
                    ("MATCHING", "Matching"),
                    ("PROCESSED", "Processed"),
                    ("ANALYSIS_FAILED", "Analysis Failed"),
                ],
                default="UPLOADED",
                max_length=20,
            ),
        ),
    ]
