# Generated by Django 5.2.15 on 2026-07-08 19:01

import apps.exports.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boq', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_sheet', models.FileField(blank=True, null=True, upload_to=apps.exports.models.export_upload_path)),
                ('client_sheet', models.FileField(blank=True, null=True, upload_to=apps.exports.models.export_upload_path)),
                ('exported_at', models.DateTimeField(auto_now_add=True)),
                ('boq_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='boq.boqrun')),
                ('exported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-exported_at'],
            },
        ),
    ]
