# Generated by Django 5.2.15 on 2026-06-23 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boq', '0001_initial'),
        ('database_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=150)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('boq_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_matches', to='boq.boqitem')),
            ],
        ),
        migrations.CreateModel(
            name='ProductMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('make', models.CharField(blank=True, max_length=150)),
                ('vendor', models.CharField(blank=True, max_length=150)),
                ('match_reason', models.CharField(blank=True, max_length=255)),
                ('ai_explanation', models.TextField(blank=True)),
                ('boq_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_matches', to='boq.boqitem')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='database_manager.ratemaster')),
            ],
            options={
                'ordering': ['boq_item', '-confidence_score'],
            },
        ),
    ]
