# Generated by Django 5.2.15 on 2026-06-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmatch',
            name='custom_maker',
            field=models.CharField(blank=True, help_text='Custom maker name entered by the Expert during review.', max_length=255),
        ),
        migrations.AddField(
            model_name='productmatch',
            name='vendor_mode',
            field=models.CharField(blank=True, choices=[('LOWEST_COST', 'Lowest Cost'), ('PREFERRED', 'Preferred Vendor'), ('CUSTOM', 'Custom Selection')], default='LOWEST_COST', max_length=20),
        ),
    ]
