# Generated by Django 5.2.15 on 2026-06-23 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('labour_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('transportation_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('accessories_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('overhead_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('final_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('product_match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cost_breakdown', to='matching.productmatch')),
            ],
        ),
    ]
