# Generated by Django 5.2.15 on 2026-07-08 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labour_master_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('tech_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('make', models.CharField(blank=True, max_length=150)),
                ('supplier', models.CharField(blank=True, max_length=150)),
                ('base_purchase_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('net_material_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('commercial_material_base', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('accessories_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('handling_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('wastage_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('subtotal_before_profit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('final_expenditure', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('final_amount_excl_gst', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('margin_percent_on_selling', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('labour_type', models.CharField(blank=True, max_length=100)),
                ('labour_state', models.CharField(blank=True, max_length=100)),
                ('labour_rate_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_labour_per_unit', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_labour_with_multiplier', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('rate_contribution', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('product_match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rate_detail', to='matching.productmatch')),
            ],
        ),
    ]
