# Generated by Django 5.2.15 on 2026-07-03 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_superadmin_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allow_db_access',
            field=models.BooleanField(default=False),
        ),
    ]
